version: "3"
services:
  ocular-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ocular
      POSTGRES_USER: ocular
      POSTGRES_DB: ocular

  ocular-db-migration:
    container_name: ocular-db-migration
    depends_on:
      - ocular-db
    build:
      context: .
      dockerfile: packages/ocular/Dockerfile
    environment:
      - DATABASE_URL=postgresql://ocular:ocular@ocular-db:5432/ocular
      - DATABASE_NAME=ocular
    command: npm run typeorm migration:run

  ocular-backend:
    container_name: ocular-backend
    build:
      context: .
      dockerfile: packages/ocular/Dockerfile
    depends_on:
      ocular-db:
        condition: service_started
      ocular-db-migration:
        condition: service_completed_successfully
    ports:
      - 9000:9000
    environment:
      - DATABASE_URL=postgresql://ocular:ocular@ocular-db:5432/ocular
      - DATABASE_NAME=ocular

  ocular-ui:
    container_name: ocular-ui
    build:
      context: .
      dockerfile: packages/ocular-ui/Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - ocular-backend
